<script type="text/javascript" src="jquery-3.4.1.js"></script>

	
<?php
include("conexion.php");
$bodega='E005';
$c=$conexion1->query("select * from consny.articulo where year(recordDate)=2020 and articulo='FARD0-1051'")or die($conexion1->error());
$cb=$conexion1->query("select * from usuariobodega where bodega ='$bodega' ")or die($conexion1->error());
$fcb=$cb->FETCH(PDO::FETCH_ASSOC);
$hamachi=$fcb['HAMACHI'];
$bd=$fcb['BASE'];
try {
	$conexion_tienda=new PDO("sqlsrv:Server=$hamachi;Database=$bd", "sa", "$0ftland");
} catch (Exception $e) {
	echo "ERROR CONEXION TIENDA";
}


while($f=$c->FETCH(PDO::FETCH_ASSOC))
{
	$art=$f['ARTICULO'];
	$q=$conexion_tienda->query("select * from consny.articulo where articulo='$art'")or die($conexion_tienda->error());
	$nq=$q->rowCount();
	if($nq==0)
	{
		echo "$art";
		$plantilla_serie=$f['PLANTILLA_SERIE'];
		if($plantilla_serie=='')
		{
			$plantilla_serie='NULL';
		}else
		{
			$plantilla_serie="'$plantilla_serie'";
		}

		$descripcion=$f['DESCRIPCION'];
		if($descripcion=='')
		{
			$descripcion='NULL';
		}else
		{
			$descripcion="'$descripcion'";
		}
		$clasificacion_1=$f['CLASIFICACION_1'];
		if($clasificacion_1=='')
		{
			$clasificacion_1='NULL';
		}else
		{
			$clasificacion_1="'$clasificacion_1'";
		}
		$clasificacion_2=$f['CLASIFICACION_2'];
		if($clasificacion_2=='')
		{
			$clasificacion_2='NULL';
		}else
		{
			$clasificacion_2="'$clasificacion_2'";
		}
		$clasificacion_3=$f['CLASIFICACION_3'];
		if($clasificacion_3=='')
		{
			$clasificacion_3='NULL';
		}else
		{
			$clasificacion_3="'$clasificacion_3'";
		}
		$clasificacion_4=$f['CLASIFICACION_4'];
		if($clasificacion_4=='')
		{
			$clasificacion_4='NULL';
		}else
		{
			$clasificacion_4="'$clasificacion_4'";
		}
		$clasificacion_5=$f['CLASIFICACION_5'];
		if($clasificacion_5=='')
		{
			$clasificacion_5='NULL';
		}else
		{
			$clasificacion_5="'$clasificacion_5'";
		}
		$clasificacion_6=$f['CLASIFICACION_6'];
		if($clasificacion_6=='')
		{
			$clasificacion_6='NULL';
		}else
		{
			$clasificacion_6="'$clasificacion_6'";
		}
		$factor_conver_1=$f['FACTOR_CONVER_1'];
		if($factor_conver_1=='')
		{
			$factor_conver_1='NULL';
		}else
		{
			$factor_conver_1="'$factor_conver_1'";
		}
		$factor_conver_2=$f['FACTOR_CONVER_2'];
		if($factor_conver_2=='')
		{
			$factor_conver_2='NULL';
		}else
		{
			$factor_conver_2="'$factor_conver_2'";
		}
		$factor_conver_3=$f['FACTOR_CONVER_3'];
		if($factor_conver_3=='')
		{
			$factor_conver_3='NULL';
		}else
		{
			$factor_conver_3="'$factor_conver_3'";
		}
		$factor_conver_4=$f['FACTOR_CONVER_4'];
		if($factor_conver_4=='')
		{
			$factor_conver_4='NULL';
		}else
		{
			$factor_conver_4="'$factor_conver_4'";
		}
		$factor_conver_5=$f['FACTOR_CONVER_5'];
		if($factor_conver_5=='')
		{
			$factor_conver_5='NULL';
		}else
		{
			$factor_conver_5="'$factor_conver_5'";
		}
		$factor_conver_6=$f['FACTOR_CONVER_6'];
		if($factor_conver_6=='')
		{
			$factor_conver_6='NULL';
		}else
		{
			$factor_conver_6="'$factor_conver_6'";
		}
		$tipo=$f['TIPO'];
		if($tipo=='')
		{
			$tipo='NULL';
		}else
		{
			$tipo="'$tipo'";
		}
		$origen_corp=$f['ORIGEN_CORP'];
		if($origen_corp=='')
		{
			$origen_corp='NULL';
		}else
		{
			$origen_corp="'$origen_corp'";
		}
		$peso_neto=$f['PESO_NETO'];
		if($peso_neto=='')
		{
			$peso_neto='NULL';
		}else
		{
			$peso_neto="'$peso_neto'";
		}
		$peso_bruto=$f['PESO_BRUTO'];
		if($peso_bruto=='')
		{
			$peso_bruto='NULL';
		}else
		{
			$peso_bruto="'$peso_bruto'";
		}
		$volumen=$f['VOLUMEN'];
		if($volumen=='')
		{
			$volumen='NULL';
		}else
		{
			$volumen="'$volumen'";
		}		
		$bultos=$f['BULTOS'];
		if($bultos=='')
		{
			$bultos='NULL';
		}else
		{
			$bultos="'$bultos'";
		}
		$articulo_cuenta=$f['ARTICULO_CUENTA'];
		if($articulo_cuenta=='')
		{
			$articulo_cuenta='NULL';
		}else
		{
			$articulo_cuenta="'$articulo_cuenta'";
		}
		$impuesto=$f['IMPUESTO'];
		if($impuesto=='')
		{
			$impuesto='NULL';
		}else
		{
			$impuesto="'$impuesto'";
		}
		$factor_empaque=$f['FACTOR_EMPAQUE'];
		if($factor_empaque=='')
		{
			$factor_empaque='NULL';
		}else
		{
			$factor_empaque="'$factor_empaque'";
		}
		$factor_venta=$f['FACTOR_VENTA'];
		if($factor_venta=='')
		{
			$factor_venta='NULL';
		}else
		{
			$factor_venta="'$factor_venta'";
		}
		$existencia_minima=$f['EXISTENCIA_MINIMA'];
		if($existencia_minima=='')
		{
			$existencia_minima='NULL';
		}else
		{
			$existencia_minima="'$existencia_minima'";
		}
		$existencia_maxima=$f['EXISTENCIA_MAXIMA'];
		if($existencia_maxima=='')
		{
			$existencia_maxima='NULL';
		}else
		{
			$existencia_maxima="'$existencia_maxima'";
		}
		$punto_de_reorden=$f['PUNTO_DE_REORDEN'];
		if($punto_de_reorden=='')
		{
			$punto_de_reorden='NULL';
		}else
		{
			$punto_de_reorden="'$punto_de_reorden'";
		}
		$costo_fiscal=$f['COSTO_FISCAL'];
		if($costo_fiscal=='')
		{
			$costo_fiscal='NULL';
		}else
		{
			$costo_fiscal="'$costo_fiscal'";
		}
		$costo_comparativo=$['COSTO_COMPARATIVO'];
		if($costo_comparativo=='')
		{
			$costo_comparativo='NULL';
		}else
		{
			$costo_comparativo="'$costo_comparativo'";
		}
		$costo_prom_loc=$f['COSTO_PROM_LOC'];
		if($costo_prom_loc=='')
		{
			$costo_prom_loc='NULL';
		}else
		{
			$costo_prom_loc="'$costo_prom_loc'";
		}

		$costo_promo_dol=$f['COSTO_PROM_DOL'];
		if($costo_promo_dol=='')
		{
			$costo_promo_dol='NULL';
		}else
		{
			$costo_promo_dol="'$costo_promo_dol'";
		}
		$costo_std_loc=$f['COSTO_STD_LOC'];
		if($costo_std_loc=='')
		{
			$costo_std_loc='NULL';
		}else
		{
			$costo_std_loc="'$costo_std_loc'";
		}
		$costo_std_dol=$f['COSTO_STD_DOL'];
		if($costo_std_dol=='')
		{
			$costo_std_dol='NULL';
		}else
		{
			$costo_std_dol="'$costo_std_dol'";
		}
		$costo_ult_loc=$f['COSTO_ULT_LOC'];
		if($costo_ult_loc=='')
		{
			$costo_ult_loc='NULL';
		}else
		{
			$costo_ult_loc="'$costo_ult_loc'";
		}
		$costo_ult_dol=$f['COSTO_ULT_DOL'];
		if($costo_ult_dol=='')
		{
			$costo_ult_dol='NULL';
		}else
		{
			$costo_ult_dol="'$costo_ult_dol'";
		}
		$precio_base_local=$f['PRECIO_BASE_LOCAL'];
		if($precio_base_local=='')
		{
			$precio_base_local='NULL';
		}else
		{
			$precio_base_local="'$precio_base_local'";
		}
		$precio_base_dolar=$f['PRECIO_BASE_DOLAR'];
		if($precio_base_dolar=='')
		{
			$precio_base_dolar='NULL';
		}else
		{
			$precio_base_dolar="'$precio_base_dolar'";
		}
		$ultima_salida=$f['ULTIMA_SALIDA'];
		if($ultima_salida=='')
		{
			$ultima_salida='NULL';
		}else
		{
			$ultima_salida="'$ultima_salida'";
		}
		$ultimo_movimiento=$f['ULTIMO_MOVIMIENTO'];
		if($ultimo_movimiento=='')
		{
			$ultimo_movimiento='NULL';
		}else
		{
			$ultimo_movimiento="'$ultimo_movimiento'";
		}
		$ultimo_ingreso=$f['ULTIMO_INGRESO';
		if($ultimo_ingreso=='')
		{
			$ultimo_ingreso='NULL';
		}else
		{
			$ultimo_ingreso="'$ultimo_ingreso'";
		}
		$ultimo_inventario=$f['ULTIMO_INVENTARIO'];
		if($ultimo_inventario=='')
		{
			$ultimo_inventario='NULL';
		}else
		{
			$ultimo_inventario="'$ultimo_inventario'";
		}
		$clase_abc=$f['CLASE_ABC'];
		if($clase_abc=='')
		{
			$clase_abc='NULL';
		}else
		{
			$clase_abc="'$clase_abc'";
		}
		$frecuencia_conteo=$f['FRECUENCIA_CONTEO'];
		if($frecuencia_conteo=='')
		{
			$frecuencia_conteo='NULL';
		}else
		{
			$frecuencia_conteo="'$frecuencia_conteo'";
		}
		$codigo_barras_vent=$f['CODIGO_BARRAS_VENT'];
		if($codigo_barras_vent=='')
		{
			$codigo_barras_vent='NULL';
		}else
		{
			$codigo_barras_vent="'$codigo_barras_vent'";
		}
		$codigo_barra_invt=$f['CODIGO_BARRAS_INVT'];
		if($codigo_barra_invt=='')
		{
			$codigo_barra_invt='NULL';
		}else
		{
			$codigo_barra_invt="'$codigo_barra_invt'";
		}
		$activo=$f['ACTIVO'];
		if($activo=='')
		{
			$activo='NULL';
		}else
		{
			$activo="'$activo'";
		}
		$usa_lotes=$f['USA_LOTES'];
		if($usa_lotes=='')
		{
			$usa_lotes='NULL';
		}else
		{
			$usa_lotes="'$usa_lotes'";
		}
		$obliga_cuarentena=$['OBLIGA_CUARENTENA'];
		if($obliga_cuarentena=='')
		{
			$obliga_cuarentena='NULL';
		}else
		{
			$obliga_cuarentena="'$obliga_cuarentena'";
		}
		$min_vida_compra=$f['MIN_VIDA_COMPRA'];
		if($min_vida_compra=='')
		{
			$min_vida_compra='NULL';
		}else
		{
			$min_vida_compra="'$min_vida_compra'";
		}
		$min_vida_comsumo=$f['MIN_VIDA_CONSUMO'];
		if($min_vida_comsumo=='')
		{
			$min_vida_comsumo='NULL';
		}else
		{
			$min_vida_comsumo="'$min_vida_comsumo'";
		}
		$min_vida_venta=$f['MIN_VIDA_VENTA'];
		if($min_vida_venta=='')
		{
			$min_vida_venta='NULL';
		}else
		{
			$min_vida_venta="'$min_vida_venta'";
		}
		$vida_util_prom=$f['VIDA_UTIL_PROM'];
		if($vida_util_prom=='')
		{
			$vida_util_prom='NULL';
		}else
		{
			$vida_util_prom="'$vida_util_prom'";
		}
		$dias_cuarentena=$f['DIAS_CUARENTENA'];
		if($dias_cuarentena=='')
		{
			$dias_cuarentena='NULL';
		}else
		{
			$dias_cuarentena="'$dias_cuarentena'";
		}
		$proveedor=$f['PROVEEDOR'];
		if($proveedor=='')
		{
			$proveedor='NULL';
		}else
		{
			$proveedor="'$proveedor'";
		}
		$articulo_del_prov=$f['ARTICULO_DEL_PROV'];
		if($articulo_del_prov=='')
		{
			$articulo_del_prov='NULL';
		}else
		{
			$articulo_del_prov="'$articulo_del_prov'";
		}
		$orden_minima=$f['ORDEN_MINIMA'];
		if($clasificacion_6=='')
		{
			$clasificacion_6='NULL';
		}else
		{
			$clasificacion_6="'$clasificacion_6'";
		}
		$plazo_reabast=$f['PLAZO_REABAST'];
		$lote_multiplo=$f['LOTE_MULTIPLO'];
		$notas=$f['NOTAS'];
		$utilizando_manufact=$f['UTILIZADO_MANUFACT'];
		$usuario_creacion=$f['USUARIO_CREACION'];
		$fch_hora_creacion=$f['FCH_HORA_CREACION'];
		$usuario_ult_modif=$f['USUARIO_ULT_MODIF'];
		$fch_hora_ult_modif=$f['FCH_HORA_ULT_MODIF'];
		$usa_numeros_serie=$f['USA_NUMEROS_SERIE'];
		$modalidad_inv_fis=$f['MODALIDAD_INV_FIS'];
		$tipo_cod_barra_det=$f['TIPO_COD_BARRA_DET'];
		$tipo_cod_barra_alm=$f['TIPO_COD_BARRA_ALM'];
		$usa_reglas_locales=$f['USA_REGLAS_LOCALES'];
		$unidad_almacen=$f['UNIDAD_ALMACEN'];
		$unidad_empaque=$f['UNIDAD_EMPAQUE'];
		$unidad_venta=$f['UNIDAD_VENTA'];
		$percedero=$f['PERECEDERO'];
		$gtin=$f['GTIN'];
		$manufacturador=$f['MANUFACTURADOR'];
		$codigo_retencion=$f['CODIGO_RETENCION'];
		$retencion_venta=$f['RETENCION_VENTA'];
		$retencion_compra=$f['RETENCION_COMPRA'];
		$modelo_retencion=$f['MODELO_RETENCION'];
		$estilo=$f['ESTILO'];
		$talla=$f['TALLA'];
		$color=$f['COLOR'];
		$tipo_costo=$f['TIPO_COSTO'];
		$articulo_envase=$f['ARTICULO_ENVASE'];
		$es_envase=$f['ES_ENVASE'];
		$usa_control_envase=$f['USA_CONTROL_ENVASE'];
		$costo_prom_comparativo_loc=$f['COSTO_PROM_COMPARATIVO_LOC'];
		$costo_prom_comparativo_dolar=$f['COSTO_PROM_COMPARATIVO_DOLAR'];	             $costo_prom_ultimo_loc=$f['COSTO_PROM_ULTIMO_LOC'];
		$costo_prom_ultimo_dol=$f['COSTO_PROM_ULTIMO_DOL'];
		$utiliando_en_contratos=$f['UTILIZADO_EN_CONTRATOS'];
		$valida_cant_fase_py=$f['VALIDA_CANT_FASE_PY'];
	$obliga_incluir_fase_py=$f['OBLIGA_INCLUIR_FASE_PY'];
		$es_impuesto=$f['ES_IMPUESTO'];
		$tipo_doc_iva=$f['TIPO_DOC_IVA'];
		$nit=$f['NIT'];
		$casta_basica=$f['CANASTA_BASICA'];
		$es_otro_cargo=$f['ES_OTRO_CARGO'];
		$servicio_medico=$f['SERVICIO_MEDICO'];
		$precio_regular=$f['PRECIO_REGULAR'];
		$u_clave_unidad=$f['U_CLAVE_UNIDAD'];
		$u_clave_prod_serv=$f['U_CLAVE_PROD_SERV'];
		$u_clave_ps_pub=$f['U_CLAVE_PS_PUB'];
		$noteexistsflag=$f['NoteExistsFlag'];	

		/*$conexion_tienda->query("ARTICULO,
			PLANTILLA_SERIE,
			DESCRIPCION,
			CLASIFICACION_1,
			CLASIFICACION_2,
			CLASIFICACION_3,
			CLASIFICACION_4,
			CLASIFICACION_5,
			CLASIFICACION_6,
			FACTOR_CONVER_1,
			FACTOR_CONVER_2,
			FACTOR_CONVER_3,
			FACTOR_CONVER_4,
			FACTOR_CONVER_5,
			FACTOR_CONVER_6,
			TIPO,
			ORIGEN_CORP,
			PESO_NETO,
			PESO_BRUTO,
			VOLUMEN,
			BULTOS,
			ARTICULO_CUENTA,
			IMPUESTO,
			FACTOR_EMPAQUE,
			FACTOR_VENTA,
			EXISTENCIA_MINIMA,
			EXISTENCIA_MAXIMA,
			PUNTO_DE_REORDEN,
			COSTO_FISCAL,
			COSTO_COMPARATIVO,
			COSTO_PROM_LOC,
			COSTO_PROM_DOL,
			COSTO_STD_LOC,
			COSTO_STD_DOL,
			COSTO_ULT_LOC,
			COSTO_ULT_DOL,
			PRECIO_BASE_LOCAL,
			PRECIO_BASE_DOLAR,
			ULTIMA_SALIDA,
			ULTIMO_MOVIMIENTO,
			ULTIMO_INGRESO,
			ULTIMO_INVENTARIO,
			CLASE_ABC,
			FRECUENCIA_CONTEO,
			CODIGO_BARRAS_VENT,
			CODIGO_BARRAS_INVT,
			ACTIVO,
			USA_LOTES,
			OBLIGA_CUARENTENA,
			MIN_VIDA_COMPRA,
			MIN_VIDA_CONSUMO,
			MIN_VIDA_VENTA,
			VIDA_UTIL_PROM,
			DIAS_CUARENTENA,
			PROVEEDOR,
			ARTICULO_DEL_PROV,
			ORDEN_MINIMA,
			PLAZO_REABAST,
			LOTE_MULTIPLO,
			NOTAS,
			UTILIZADO_MANUFACT,
			USUARIO_CREACION,
			FCH_HORA_CREACION,
			USUARIO_ULT_MODIF,
			FCH_HORA_ULT_MODIF,
			USA_NUMEROS_SERIE,
			MODALIDAD_INV_FIS,
			TIPO_COD_BARRA_DET,
			TIPO_COD_BARRA_ALM,
			USA_REGLAS_LOCALES,
			UNIDAD_ALMACEN,
			UNIDAD_EMPAQUE,
			UNIDAD_VENTA,
			PERECEDERO,
			GTIN,
			MANUFACTURADOR,
			CODIGO_RETENCION,
			RETENCION_VENTA,
			RETENCION_COMPRA,
			MODELO_RETENCION,
			ESTILO,
			TALLA,
			COLOR,
			TIPO_COSTO,
			ARTICULO_ENVASE,
			ES_ENVASE,
			USA_CONTROL_ENVASE,
			COSTO_PROM_COMPARATIVO_LOC,	COSTO_PROM_COMPARATIVO_DOLAR,	COSTO_PROM_ULTIMO_LOC,
			COSTO_PROM_ULTIMO_DOL,
			UTILIZADO_EN_CONTRATOS,
			VALIDA_CANT_FASE_PY,
			OBLIGA_INCLUIR_FASE_PY,
			ES_IMPUESTO,
			TIPO_DOC_IVA,
			NIT,
			CANASTA_BASICA,
			ES_OTRO_CARGO,
			SERVICIO_MEDICO,
			PRECIO_REGULAR,
			U_CLAVE_UNIDAD,
			U_CLAVE_PROD_SERV,
			U_CLAVE_PS_PUB,
			NoteExistsFlag")or die($conexion_tienda->error())*/
	}
	
}
?>